/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage;

import com.microsoft.rest.v2.RestProxy;
import com.microsoft.rest.v2.ServiceClient;
import com.microsoft.rest.v2.http.HttpPipeline;
import io.reactivex.annotations.NonNull;

/**
 * Initializes a new instance of the GeneratedStorageClient type.
 */
public final class GeneratedStorageClient extends ServiceClient {
    /**
     * Specifies the version of the operation to use for this request.
     */
    private String version;

    /**
     * Gets Specifies the version of the operation to use for this request.
     *
     * @return the version value.
     */
    public String version() {
        return this.version;
    }

    /**
     * Sets Specifies the version of the operation to use for this request.
     *
     * @param version the version value.
     * @return the service client itself.
     */
    public GeneratedStorageClient withVersion(String version) {
        this.version = version;
        return this;
    }

    /**
     * The URL of the service account, share, directory or file that is the target of the desired operation.
     */
    private String url;

    /**
     * Gets The URL of the service account, share, directory or file that is the target of the desired operation.
     *
     * @return the url value.
     */
    public String url() {
        return this.url;
    }

    /**
     * Sets The URL of the service account, share, directory or file that is the target of the desired operation.
     *
     * @param url the url value.
     * @return the service client itself.
     */
    public GeneratedStorageClient withUrl(String url) {
        this.url = url;
        return this;
    }

    /**
     * The GeneratedServices object to access its operations.
     */
    private GeneratedServices generatedServices;

    /**
     * Gets the GeneratedServices object to access its operations.
     *
     * @return the GeneratedServices object.
     */
    public GeneratedServices generatedServices() {
        return this.generatedServices;
    }

    /**
     * The GeneratedShares object to access its operations.
     */
    private GeneratedShares generatedShares;

    /**
     * Gets the GeneratedShares object to access its operations.
     *
     * @return the GeneratedShares object.
     */
    public GeneratedShares generatedShares() {
        return this.generatedShares;
    }

    /**
     * The GeneratedDirectorys object to access its operations.
     */
    private GeneratedDirectorys generatedDirectorys;

    /**
     * Gets the GeneratedDirectorys object to access its operations.
     *
     * @return the GeneratedDirectorys object.
     */
    public GeneratedDirectorys generatedDirectorys() {
        return this.generatedDirectorys;
    }

    /**
     * The GeneratedFiles object to access its operations.
     */
    private GeneratedFiles generatedFiles;

    /**
     * Gets the GeneratedFiles object to access its operations.
     *
     * @return the GeneratedFiles object.
     */
    public GeneratedFiles generatedFiles() {
        return this.generatedFiles;
    }

    /**
     * Initializes an instance of GeneratedStorageClient client.
     */
    public GeneratedStorageClient() {
        this(RestProxy.createDefaultPipeline());
    }

    /**
     * Initializes an instance of GeneratedStorageClient client.
     *
     * @param httpPipeline The HTTP pipeline to send requests through.
     */
    public GeneratedStorageClient(@NonNull HttpPipeline httpPipeline) {
        super(httpPipeline);
        this.generatedServices = new GeneratedServices(this);
        this.generatedShares = new GeneratedShares(this);
        this.generatedDirectorys = new GeneratedDirectorys(this);
        this.generatedFiles = new GeneratedFiles(this);
    }
}
