/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.file.models;

import com.microsoft.rest.v2.RestResponse;
import com.microsoft.rest.v2.http.HttpRequest;
import java.util.Map;

/**
 * Contains all response data for the listFilesAndDirectoriesSegment operation.
 */
public final class DirectoryListFilesAndDirectoriesSegmentResponse extends RestResponse<DirectoryListFilesAndDirectoriesSegmentHeaders, ListFilesAndDirectoriesSegmentResponse> {
    /**
     * Creates an instance of DirectoryListFilesAndDirectoriesSegmentResponse.
     *
     * @param request the request which resulted in this {response.Name}.
     * @param statusCode the status code of the HTTP response.
     * @param headers the deserialized headers of the HTTP response.
     * @param rawHeaders the raw headers of the HTTP response.
     * @param body the deserialized body of the HTTP response.
     */
    public DirectoryListFilesAndDirectoriesSegmentResponse(HttpRequest request, int statusCode, DirectoryListFilesAndDirectoriesSegmentHeaders headers, Map<String, String> rawHeaders, ListFilesAndDirectoriesSegmentResponse body) {
        super(request, statusCode, headers, rawHeaders, body);
    }

    /**
     * @return the deserialized response headers.
     */
    @Override
    public DirectoryListFilesAndDirectoriesSegmentHeaders headers() {
        return super.headers();
    }

    /**
     * @return the deserialized response body.
     */
    @Override
    public ListFilesAndDirectoriesSegmentResponse body() {
        return super.body();
    }
}
