/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.file.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import java.util.ArrayList;
import java.util.List;

/**
 * Abstract for entries that can be listed from Directory.
 */
@JacksonXmlRootElement(localName = "Entries")
public final class Entries {
    /**
     * The directoryItems property.
     */
    @JsonProperty("Directory")
    private List<DirectoryItem> directoryItems = new ArrayList<>();

    /**
     * The fileItems property.
     */
    @JsonProperty("File")
    private List<FileItem> fileItems = new ArrayList<>();

    /**
     * Get the directoryItems value.
     *
     * @return the directoryItems value.
     */
    public List<DirectoryItem> directoryItems() {
        return this.directoryItems;
    }

    /**
     * Set the directoryItems value.
     *
     * @param directoryItems the directoryItems value to set.
     * @return the Entries object itself.
     */
    public Entries withDirectoryItems(List<DirectoryItem> directoryItems) {
        this.directoryItems = directoryItems;
        return this;
    }

    /**
     * Get the fileItems value.
     *
     * @return the fileItems value.
     */
    public List<FileItem> fileItems() {
        return this.fileItems;
    }

    /**
     * Set the fileItems value.
     *
     * @param fileItems the fileItems value to set.
     * @return the Entries object itself.
     */
    public Entries withFileItems(List<FileItem> fileItems) {
        this.fileItems = fileItems;
        return this;
    }
}
