/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.file.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;

/**
 * Additional parameters for a set of operations, such as: File_create,
 * File_setHTTPHeaders.
 */
@JacksonXmlRootElement(localName = "file-HTTP-headers")
public final class FileHTTPHeaders {
    /**
     * Sets the MIME content type of the file. The default type is
     * 'application/octet-stream'.
     */
    @JsonProperty(value = "FileContentType")
    private String fileContentType;

    /**
     * Specifies which content encodings have been applied to the file.
     */
    @JsonProperty(value = "FileContentEncoding")
    private String fileContentEncoding;

    /**
     * Specifies the natural languages used by this resource.
     */
    @JsonProperty(value = "FileContentLanguage")
    private String fileContentLanguage;

    /**
     * Sets the file's cache control. The File service stores this value but
     * does not use or modify it.
     */
    @JsonProperty(value = "FileCacheControl")
    private String fileCacheControl;

    /**
     * Sets the file's MD5 hash.
     */
    @JsonProperty(value = "FileContentMD5")
    private byte[] fileContentMD5;

    /**
     * Sets the file's Content-Disposition header.
     */
    @JsonProperty(value = "FileContentDisposition")
    private String fileContentDisposition;

    /**
     * Get the fileContentType value.
     *
     * @return the fileContentType value.
     */
    public String fileContentType() {
        return this.fileContentType;
    }

    /**
     * Set the fileContentType value.
     *
     * @param fileContentType the fileContentType value to set.
     * @return the FileHTTPHeaders object itself.
     */
    public FileHTTPHeaders withFileContentType(String fileContentType) {
        this.fileContentType = fileContentType;
        return this;
    }

    /**
     * Get the fileContentEncoding value.
     *
     * @return the fileContentEncoding value.
     */
    public String fileContentEncoding() {
        return this.fileContentEncoding;
    }

    /**
     * Set the fileContentEncoding value.
     *
     * @param fileContentEncoding the fileContentEncoding value to set.
     * @return the FileHTTPHeaders object itself.
     */
    public FileHTTPHeaders withFileContentEncoding(String fileContentEncoding) {
        this.fileContentEncoding = fileContentEncoding;
        return this;
    }

    /**
     * Get the fileContentLanguage value.
     *
     * @return the fileContentLanguage value.
     */
    public String fileContentLanguage() {
        return this.fileContentLanguage;
    }

    /**
     * Set the fileContentLanguage value.
     *
     * @param fileContentLanguage the fileContentLanguage value to set.
     * @return the FileHTTPHeaders object itself.
     */
    public FileHTTPHeaders withFileContentLanguage(String fileContentLanguage) {
        this.fileContentLanguage = fileContentLanguage;
        return this;
    }

    /**
     * Get the fileCacheControl value.
     *
     * @return the fileCacheControl value.
     */
    public String fileCacheControl() {
        return this.fileCacheControl;
    }

    /**
     * Set the fileCacheControl value.
     *
     * @param fileCacheControl the fileCacheControl value to set.
     * @return the FileHTTPHeaders object itself.
     */
    public FileHTTPHeaders withFileCacheControl(String fileCacheControl) {
        this.fileCacheControl = fileCacheControl;
        return this;
    }

    /**
     * Get the fileContentMD5 value.
     *
     * @return the fileContentMD5 value.
     */
    public byte[] fileContentMD5() {
        return this.fileContentMD5;
    }

    /**
     * Set the fileContentMD5 value.
     *
     * @param fileContentMD5 the fileContentMD5 value to set.
     * @return the FileHTTPHeaders object itself.
     */
    public FileHTTPHeaders withFileContentMD5(byte[] fileContentMD5) {
        this.fileContentMD5 = fileContentMD5;
        return this;
    }

    /**
     * Get the fileContentDisposition value.
     *
     * @return the fileContentDisposition value.
     */
    public String fileContentDisposition() {
        return this.fileContentDisposition;
    }

    /**
     * Set the fileContentDisposition value.
     *
     * @param fileContentDisposition the fileContentDisposition value to set.
     * @return the FileHTTPHeaders object itself.
     */
    public FileHTTPHeaders withFileContentDisposition(String fileContentDisposition) {
        this.fileContentDisposition = fileContentDisposition;
        return this;
    }
}
