/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.file.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import java.util.Map;

/**
 * A listed Azure Storage share item.
 */
@JacksonXmlRootElement(localName = "Share")
public final class ShareItem {
    /**
     * The name property.
     */
    @JsonProperty(value = "Name", required = true)
    private String name;

    /**
     * The snapshot property.
     */
    @JsonProperty(value = "Snapshot")
    private String snapshot;

    /**
     * The properties property.
     */
    @JsonProperty(value = "Properties", required = true)
    private ShareProperties properties;

    /**
     * The metadata property.
     */
    @JsonProperty(value = "Metadata")
    private Map<String, String> metadata;

    /**
     * Get the name value.
     *
     * @return the name value.
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set.
     * @return the ShareItem object itself.
     */
    public ShareItem withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the snapshot value.
     *
     * @return the snapshot value.
     */
    public String snapshot() {
        return this.snapshot;
    }

    /**
     * Set the snapshot value.
     *
     * @param snapshot the snapshot value to set.
     * @return the ShareItem object itself.
     */
    public ShareItem withSnapshot(String snapshot) {
        this.snapshot = snapshot;
        return this;
    }

    /**
     * Get the properties value.
     *
     * @return the properties value.
     */
    public ShareProperties properties() {
        return this.properties;
    }

    /**
     * Set the properties value.
     *
     * @param properties the properties value to set.
     * @return the ShareItem object itself.
     */
    public ShareItem withProperties(ShareProperties properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Get the metadata value.
     *
     * @return the metadata value.
     */
    public Map<String, String> metadata() {
        return this.metadata;
    }

    /**
     * Set the metadata value.
     *
     * @param metadata the metadata value to set.
     * @return the ShareItem object itself.
     */
    public ShareItem withMetadata(Map<String, String> metadata) {
        this.metadata = metadata;
        return this;
    }
}
