/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.file.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;

/**
 * Stats for the share.
 */
@JacksonXmlRootElement(localName = "ShareStats")
public final class ShareStats {
    /**
     * The approximate size of the data stored on the share, rounded up to the
     * nearest gigabyte. Note that this value may not include all recently
     * created or recently resized files.
     */
    @JsonProperty(value = "ShareUsage", required = true)
    private int shareUsage;

    /**
     * Get the shareUsage value.
     *
     * @return the shareUsage value.
     */
    public int shareUsage() {
        return this.shareUsage;
    }

    /**
     * Set the shareUsage value.
     *
     * @param shareUsage the shareUsage value to set.
     * @return the ShareStats object itself.
     */
    public ShareStats withShareUsage(int shareUsage) {
        this.shareUsage = shareUsage;
        return this;
    }
}
